// This module gathers basic information about the orthogroups generated by init_ortho
// It gets info such as deflines mapped to input sample names, which OGs from each tool the sequence is part of
// Downstream processes will use this basic information to generate reports of ortholog calling performance in which_ortho

process GET_ORTHOGROUP_INFO {

    publishDir (
        path: "${params.outdir}",
        pattern: "${output_file}",
        mode: 'copy',
        saveAs: { fn -> fn }
    )

    input:
    path(orthogroup_fasta_dir)
    val output_file
    
    output:
    path("${output_file}"), emit: orthogroups_tsv
    
    script:
    """
    mkdir -p \$(dirname "${output_file}")
    python3 ${projectDir}/bin/get_og_deflines.py ${orthogroup_fasta_dir} -o ${output_file}
    """
}