// This module gathers basic information about the orthogroups generated by init_ortho
// It gets info such as deflines mapped to input sample names, which OGs from each tool the sequence is part of
// Downstream processes will use this basic information to generate reports of ortholog calling performance in which_ortho

process GET_ORTHOGROUP_INFO {

    publishDir (
        path: "${params.outdir}/${publish_subdir}",
        mode: 'copy',
        saveAs: { fn -> fn }
    )

    input:
    path(orthogroup_fasta_dir)
    val output_dir
    val publish_subdir
    
    output:
    path("${output_dir}/Orthogroups.tsv"), emit: orthogroups_tsv
    path("${output_dir}/Orthogroups.GeneCount.tsv"), emit: orthogroups_genecount_tsv
    
    script:
    """
    mkdir -p ${output_dir}
    python3 ${projectDir}/bin/get_og_deflines.py ${orthogroup_fasta_dir} -o ${output_dir}
    """
}