// This module gathers basic information about the orthogroups generated by init_ortho
// It gets info such as deflines mapped to input sample names, which OGs from each tool the sequence is part of
// Downstream processes will use this basic information to generate reports of ortholog calling performance in which_ortho

process GET_ORTHOGROUP_INFO {
    
    input:
    path(combined_deflines)
    tuple val(meta), path(orthofinder_orthogroups)
    path(broccoli_orthogroups)
    tuple val(meta), path(dmnd_mcl_clusters)
    tuple val(meta), path(mmseqs_clusters)
    val(search_status)
    
    output:
    path("orthogroups_deflines.csv"), emit: orthogroups_deflines
    path("orthogroups.csv"), emit: orthogroups
    
    script:
    
    def orthofinder = orthofinder_orthogroups ? "${orthofinder_orthogroups}/Phylogenetic_Hierarchical_Orthogroups/N0.tsv" : ''
    def broccoli = broccoli_orthogroups ? "--broccoli ${broccoli_orthogroups}" : ''
    def diamond_mcl = dmnd_mcl_clusters ? "--diamond_mcl ${dmnd_mcl_clusters}" : ''
    def mmseqs = mmseqs_clusters ? "--mmseqs ${mmseqs_clusters}" : ''
    def search = search_status ? "--search" : ''
    """
    cut --complement -f 1,3,4,5,6 ${orthofinder} > N0.tsv.tmp

    python3 ${projectDir}/bin/get_og_deflines.py \
        --input ${combined_deflines} \
        --orthofinder N0.tsv.tmp \
        ${broccoli} \
        ${diamond_mcl} \
        ${mmseqs} \
        ${search}
    """
}