---
title: "Orthology Results: Assessing the initial orthogroups (homogroups) 155 metazoans"
author: "Dean Mckeown"
date: "`r Sys.Date()`"
output: 
  html_document:
    output_file: "results/homogroups.html"
    toc: true
    toc_float: TRUE
    toc_depth: 4
    number_sections: true
    theme: united
    highlight: tango
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, fig.path = "results/")

getwd()

```

```{css, echo=FALSE}
.scroll-200 {
  max-height: 200px;
  overflow-y: auto;
  background-color: inherit;
}
```

___



```{r Preparation, include = FALSE}
source('R/hg_data_prep.R')
suppressPackageStartupMessages(suppressWarnings(source('R/homogroup-functions.R')))


################################################################################
# INPUTS
################################################################################

################################################################################
# General inputs
################################################################################
# Colour palette (must match taxonomy in samplesheet1)

SUPERGROUP_COLS <- c(
  Choanoflagellata = "#A6CEE3",
  Cnidaria = "#1F78B4",
  Ctenophora = "#B2DF8A",
  Deuterostomia = "#33A02C",
  Filasterea = "#FB9A99",
  Placozoa = "#E31A1C",
  Porifera = "#FF7F00",
  Protostomia = "#CAB2D6",
  Teretosporea = "#6A3D9A"
)


OG_CALLER_COLS <- c(
  orthofinder = "#D95F02",
  broccoli = "#1B9E77"
)
# this is colored blocks in a single row to label axis via patchwork
axis_lab_id_sg <- main_seq_long %>%
  select(id, supergroup) %>%
  distinct() %>%
  mutate(id = factor(id, levels = unique(main_seq_long %>% arrange(supergroup) %>% pull(id)))) %>%
  ggplot(aes(x = id, y = 1, fill = supergroup)) +
  geom_tile(width = 1, height = 1) +
  scale_fill_manual(values = SUPERGROUP_COLS) +
  theme_minimal() +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(face = "bold", size = 10),
        panel.grid = element_blank(),
        plot.margin = margin(t = 0, b = 0)) +
  ylab("Supergroup")





################################################################################
# OUTPUTS
################################################################################
# And where summarized results should be saved.
OUTPUT_DIR <- './results/'
dir.create(OUTPUT_DIR, showWarnings = F)

```


```{r Species tree}
tree <- read.tree(SPECIES_TREE)

tree_meta <- list()

tree_meta$tips <- main_seq_long %>%
  select(
    id,
    supergroup
  ) %>%
  unique()

# prepare data for heatmap
# per geneclass
tree_meta$hm_total_genes_in_id_by_geneclass <- main_seq_long %>%
  select(id, most_common_pfam_hmm_name, clean_parent_seq) %>%
  unique() %>%
  group_by(id, most_common_pfam_hmm_name) %>%
  summarise(values = n_distinct(clean_parent_seq), .groups = 'drop') %>%
  pivot_wider(names_from = most_common_pfam_hmm_name, values_from = values) %>%
  column_to_rownames("id") %>%
  replace(is.na(.), 0)

# per OG
tree_meta$hm_total_genes_in_id_by_og <- main_seq_long %>%
  select(id, Orthogroup, clean_parent_seq) %>%
  unique() %>%
  group_by(id, Orthogroup) %>%
  summarise(values = n_distinct(clean_parent_seq), .groups = 'drop') %>%
  pivot_wider(names_from = Orthogroup, values_from = values) %>%
  column_to_rownames("id") %>%
  replace(is.na(.), 0)

sp_tree <- tree %>%
  ggtree(aes(color = supergroup),
    linewidth = 1.0,
    layout = "rectangular"
  ) %<+% tree_meta$tips +
  geom_tiplab() +
  scale_color_manual(values = SUPERGROUP_COLS)

sp_tree <- gheatmap(sp_tree, 
  tree_meta$hm_total_genes_in_id_by_geneclass,
  offset = 8,
  width = 2,
  colnames_angle = 90,
  colnames_offset_y = -1,
  hjust = 1,
  low = "white",
  high = "blue",
  color = "white"
  )

sp_tree +
  ggtree::vexpand(.1, -1) +
  coord_cartesian(clip = "off")

# Save the tree and metadata for shiny
save(tree, tree_meta, file = "data/tree_and_metadata.RData")


```
## Orthogroup Homogeneity {.tabset}
```{r Orthogroup homogeneity}
# data reshape
og_meta <- main_seq_long %>%
  select(
    id,
    supergroup,
    Orthogroup,
    OG_source,
    cogeqc_hscore,
    cogeqc_hscore_scaled_all,
    cogeqc_hscore_scaled_self,
    total_seqs,
    total_parent_seqs,
    total_ids,
    total_supergroups,
    most_common_pfam_hmm_name,
    total_most_common_pfam_hmm_name,
    percent_most_common_pfam_hmm_name,
    vs_Orthogroup,
    vs_OG_source,
    Best_Jaccard,
    Mean_Jaccard,
    percent_total_seqs,
    percent_total_parent_seqs,
    percent_total_ids,
    percent_total_supergroups,
    og_size_category_seqs,
    og_size_category_parent_seqs
  ) %>%
  rename(og_size = total_seqs) %>%
  unique() %>%
  collapse_col(id, c("OG_source", "Orthogroup"), ",", unique_values = TRUE) %>%
  unique() %>%
  collapse_col(supergroup, c("OG_source", "Orthogroup"), ",", unique_values = TRUE) %>%
  unique()

# plot by tools
vn_cogeqc_hssc_tools <- og_meta %>% ggviolin(
    y = "cogeqc_hscore_scaled_all", x = "OG_source", 
    trim = TRUE, 
    add = "jitter",
    fill = "OG_source"
  ) +
    scale_fill_manual(values = OG_CALLER_COLS) +
    labs(y = "Scaled homogeneity scores", x = "Source of orthogroups",
         title = "Distribution of mean homogeneity scores for orthogroups") +
    theme(plot.subtitle = ggtext::element_markdown())

# plot by species, color tools
vn_cogeqc_hssc_sp <- og_meta %>%
separate_longer_delim(id, delim = ",") %>%
separate_longer_delim(supergroup, delim = ",") %>%
unique() %>%
mutate(id = factor(id, levels = unique(main_seq_long %>% arrange(supergroup) %>% pull(id)))) %>%
ggplot(aes(x = id, y = cogeqc_hscore_scaled_all, fill = OG_source)) +
  geom_violin(trim = TRUE, position = position_dodge(1)) +
  scale_fill_manual(values = OG_CALLER_COLS) +
  labs(y = "Scaled homogeneity scores", x = "Species",
       title = "Distribution of mean homogeneity scores for orthogroups") +
  theme(plot.subtitle = ggtext::element_markdown()) +
  theme_bw()

# hack to label axis with supergroup
vn_cogeqc_hssc_sp <- vn_cogeqc_hssc_sp + axis_lab_id_sg + 
plot_layout(ncol = 1, nrow = 2, heights = c(20, 0.5)) +
plot_layout(guides = "collect")

```

### OG Homogeneity by Tools
```{r}
vn_cogeqc_hssc_tools
```

### OG Homogeneity by Species
```{r}
vn_cogeqc_hssc_sp
```
---
## Orthogroup Stats {.tabset}
```{r Basic OG stats}

sp_ogs_coghs_vs_size_vs_sgs <- og_meta %>%
  ggplot(aes(x = og_size,
  y = cogeqc_hscore_scaled_all,
  size = total_supergroups,
  color = OG_source)) +
  geom_point(alpha=0.7) +
  scale_size(range = c(0, 10)) +
  scale_color_manual(values = OG_CALLER_COLS) +
  theme(legend.position = "none") +
  theme_bw()

vn_size_tools <- og_meta %>%
    ggviolin(y = "og_size", x = "OG_source", 
    trim = TRUE, 
    add = "jitter",
    fill = "OG_source"
  ) +
    scale_fill_manual(values = OG_CALLER_COLS) +
    labs(y = "Num genes in OG", x = "Source of orthogroups") +
    theme(plot.subtitle = ggtext::element_markdown()) +
    scale_y_continuous(trans = 'log10', labels = scales::comma)


```
## Orthogroup homogeneity score vs OG size
```{r}
sp_ogs_coghs_vs_size_vs_sgs
```
### Orthogroup size by tool
```{r}
vn_size_tools
```
---
## Overall Tool Similarity {.tabset}
```{r Algorithm Comparison}
# Create the heatmap using ggplot2
jaccard_metrics_heat_callers <- jaccard_metrics_all_long %>%
ggplot(aes(x = tool1, y = tool2, fill = Value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0.5) +
  facet_wrap(~Metric) +
  theme_minimal() +
  labs(
    title = "Heatmaps of Metrics by Tool Pair",
    x = "Tool 1", y = "Tool 2", fill = "Value"
  ) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(strip.text = element_text(size = 12)) +
  coord_fixed(ratio = 1)

# OG vs OG heatmap prep

hm_ogs_vs <- og_meta %>%
filter(OG_source == "orthofinder") %>%
mutate(Orthogroup = factor(Orthogroup, levels = unique(Orthogroup))) %>%
ggplot() +
  geom_tile(aes(x = "COGEQC hscore scaled vs all", y = Orthogroup, fill = cogeqc_hscore_scaled_all)) +
  scale_fill_gradient2(low = "#FFF5F0", high = "#67000D", limits = c(0, 1), midpoint = 0.25, guide = guide_colorbar(order = 5)) +

  new_scale_fill() +
  geom_tile(aes(x = "% of OG that is the most common Pfam", y = Orthogroup, fill = percent_most_common_pfam_hmm_name)) +
  scale_fill_gradient2(low = "#FCFBFD", high = "#3F007D", limits = c(0, 100), midpoint = 25, guide = guide_colorbar(order = 1)) +

  new_scale_fill() +
  geom_tile(aes(x = "OG size", y = Orthogroup, fill = og_size)) +
  scale_fill_gradient2(low = "#B2182B", high = "#2166AC", mid = "#F7F7F7", guide = guide_colorbar(order = 6)) +

  new_scale_fill() +ß
  geom_tile(aes(x = "Best JI vs ", y = Orthogroup, fill = Best_Jaccard)) +
  scale_fill_gradient2(low = "#762A83", high = "#1B7837", mid = "#F7F7F7", limits = c(0, 1), midpoint = 0.5, guide = guide_colorbar(order = 4)) +

  new_scale_fill() +
  geom_tile(aes(x = "OG source", y = Orthogroup, fill = OG_source)) +
  scale_fill_manual(values = OG_CALLER_COLS, guide = guide_legend(order = 7)) +

  new_scale_fill() +
  geom_tile(aes(x = "% species in OG", y = Orthogroup, fill = percent_total_ids)) +
    scale_fill_gradient2(low = "#F7FCF5", high = "#00441B", limits = c(0, 100), midpoint = 25, guide = guide_colorbar(order = 2)) +

  new_scale_fill() +
  geom_tile(aes(x = "% supergroups in OG", y = Orthogroup, fill = percent_total_supergroups)) +
  scale_fill_gradient2(low = "#EFF3FF", high = "#08519C", limits = c(0, 100), midpoint = 25, guide = guide_colorbar(order = 3)) +

  new_scale_fill() +
  geom_tile(aes(x = "vs OG source", y = Orthogroup, fill = vs_OG_source)) +
  scale_fill_manual(values = OG_CALLER_COLS, guide = guide_legend(order = 8)) +



  theme_bw() +
  theme(legend.position = "bottom",
  legend.direction = "vertical",
  legend.title = element_blank(),
  axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_grid(most_common_pfam_hmm_name ~ ., scales = "free", space = "free")
###



```
### Orthogroup callers jaccard heatmap
```{r}
jaccard_metrics_heat_callers
```
### Orthogroup caller versus other callers & basic stats
```{r}
hm_ogs_vs
```
## Taxonomic Distribution of OGs {.tabset}
```{r Taxonomic Distribution}
up_in_ogs <- list()
# make matrices
#      for supergroups
up_in_ogs$sg <- create_presence_matrix(main_seq_long, supergroup, Orthogroup)
up_in_ogs$sg_cols <- main_seq_long$supergroup %>% unique()
up_in_ogs$sg <- up_in_ogs$sg %>% 
  left_join(og_meta, by = c("Name" = "Orthogroup"))

#      for gene classes
up_in_ogs$gc <- create_presence_matrix(main_seq_long, pfam_hmm_name, Orthogroup)
up_in_ogs$gc_cols <- colnames(up_in_ogs$gc)[-1]
up_in_ogs$gc <- up_in_ogs$gc %>% 
  left_join(og_meta, by = c("Name" = "Orthogroup"))

up_ogs_sg <- upset(up_in_ogs$sg,
  up_in_ogs$sg_cols,
  annotations = list(
      'Orthogroup caller'=(
          ggplot(mapping=aes(fill = OG_source))
          + geom_bar(stat='count', position='fill')
          + scale_y_continuous(labels=scales::percent_format())
          + scale_fill_manual(values = OG_CALLER_COLS)
          + ylab('Orthogroup caller')
      )
  ),
)

upset_geneclasses <- upset(up_in_all,
  geneclasses,
  annotations = list(
      'Orthogroup caller'=(
          ggplot(mapping=aes(fill=OG_source))
          + geom_bar(stat='count', position='fill')
          + scale_y_continuous(labels=scales::percent_format())
          + scale_fill_manual(values = OG_CALLER_COLS)
          + ylab('Orthogroup caller')
      )
  ),
)


```